# Edit this as appropriate
#project.home: ${user.home}/dev
spring:
   config:
       name: configserver
   cloud:
       config:
           server:
               git:
                  uri: https://github.com/dturanski/config-repo
#                 uri: file://${project.home}/config-repo

server:
   port: 8888
logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.context: DEBUG
    org.springframework.web: DEBUG